name: Flowzone
on:
  workflow_call:
    inputs:
      balena_slugs:
        type: string
        default: ""
      runs_on:
        type: string
        default: '["ubuntu-latest"]'
      jobs_timeout_minutes:
        type: number
        default: 120
      max_parallel:
        type: number
        default: 20
      generate_sbom:
        type: boolean
        default: true
      working_directory:
        type: string
        default: "."
      cargo_targets:
        type: string
        default: ""

jobs:
  event_types:
    name: Event Types
    runs-on: ubuntu-latest
    outputs:
      event_name: pull_request_target
      event_action: opened
    steps:
      - run: echo "Starting workflow"

  versioned_source:
    name: Versioned source
    runs-on: ubuntu-latest
    needs: event_types
    outputs:
      tag: v2.0.20
      semver: 2.0.20
      sha: d9ca4dcdc7b393c37860f54343fcd4c1b6f7d108
      has_submodules: "false"
    steps:
      - run: echo "Versioning"

  file_list:
    name: File list
    runs-on: ubuntu-latest
    needs: event_types
    outputs:
      root: '["pyproject.toml", "requirements.txt", "setup.py", "tests/conftest.py", ".pre-commit-config.yaml"]'
      workdir: '["pyproject.toml", "requirements.txt", "setup.py", "tests/conftest.py", ".pre-commit-config.yaml"]'
    steps:
      - run: echo "File listing"

  is_python:
    name: Is python
    runs-on: ubuntu-latest
    needs: versioned_source
    outputs:
      python_poetry: "true"
      python_versions: '["3.11"]'
      pypi_publish: "true"
      python_sbom: "true"
    steps:
      - run: echo "Python check"

  python_test:
    name: Test python poetry
    runs-on: ubuntu-latest
    needs:
      - is_python
      - versioned_source
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3
      - name: Run poetry install
        run: poetry install
      - name: Run pytest
        run: poetry run pytest tests/
