[tool.poetry]
name = "balena-python-hello-world"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
flake8 = "*"
pydocstyle = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
